### ISSUE TITLE
conversationAdded event never hit?

### ISSUE THREAD

**Issue by crhistianramirez** [twilio/twilio-conversations-demo-react#26]
Hi, I'm implementing a chat application based on the code here and its going great mostly but I have an annoying little bug where it seems `conversationAdded` will sometimes not get hit (for any conversations) and I have no idea why. Is there any commonly known reason that could be causing this?

I'm initializing the twilio client in a singleton service

```typescript
async initialize(myCarmmunityUserId: string): Promise<Client> {
    return new Promise(async (resolve, reject) => {
      if (this.client) {
        return resolve(this.client);
      }
      const token = await this.getToken();
      this.client = new Client(token);
      this.client.on('stateChanged', state => {
        if (state === 'initialized') {
          this.listenToEvents(this.client);
          return resolve(this.client);
        } else if (state === 'failed') {
          return reject('Failed to initialize Twilio client');
        }
      });
    });
  }
```

And then in listenToEvents:

```typescript
listenToEvents(client: Client) {
    client.on('conversationAdded', async (conversation: Conversation) => {
        // intermittently this will not get hit happens maybe once every 4 times
    }
}
```

**Comment by Pavel-Cherentsov** [comment]
Hi @crhistianramirez!
So `conversationAdded` event is sometimes missed, sometimes hit..
In which cases do you observe it happens:
 - current user joins conversation 
 - or current user is being added to conversation by other users?

**Comment by crhistianramirez** [comment]
@Pavel-Cherentsov 

It happens on an existing conversation when I reload the page so I suppose that would be when I join the conversation.

 However the other odd piece that I've observed is that conversation.status is always "notParticipating" instead of "joined" even though user has participated in the conversation before. Maybe this is an expected status on first page load?

**Comment by Pavel-Cherentsov** [comment]
On conversation load, its status is initialised as `notParticipating` and then should be updated to `joined` (if user participates it). If not updated - it looks like a bug and needs investigation.

Is this conversation created & owned by the current user?
If yes and this conversation is not joined yet then it should be displayed as `notParticipating`.
User should explicitly join his own conversation in order to participate.

`conversationAdded` is fired when a conversation becomes visible to the user, actually when user creates conversation or is added to other user's conversation.

Once user creates conversation, `conversationAdded` event should arrive, user becomes conversation owner but does not participate it yet.
Once user joins his owned conversation, `conversationJoined` event should arrive.
Once user is added to other user's conversation, both `conversationAdded` and `conversationJoined` events should arrive.

**Comment by berkus** [comment]
@crhistianramirez there are fixes for this that would be merged shortly.

**Comment by berkus** [comment]
Fix merged!
