### ISSUE TITLE
Get conversations in the order they were last updated?

### ISSUE THREAD

**Issue by nring** [twilio/twilio-conversations-demo-react#8]
Thank you for creating this repo and sample app! It's helpful to see a new one built around Conversations 2.0.0.

In an existing application we're trying to get a list of a user's conversations and then display the most recent ones along with each conversation's most recent message. A problem we're running into is scaling this as a user belongs to 100+ conversations. We have to get that entire list, sort by the time it was last updated, then get the last message for each one of those conversations . It looks like you're doing something similar in `convoReducer.js` with `case ActionType.LIST_CONVERSATIONS:`.

We could delete a ton of client code, reduce app complexity, and (we believe) dramatically speed things up if we could have an `orderBy` parameter when fetching a list of a user's conversations. That way we could have them pre-sorted by date, then fetch the most recent message for the first 20 that we need to display.

Does this exist or _will it_ exist? The docs for the Conversations API are a bit vague on what arguments `Client.getSubscribedConversations` accepts.
```
getSubscribedConversations(args?: any): Promise<Paginator<Conversation>>
Get the current list of all the subscribed conversations.

Parameters
Optional args: any
```

**Comment by InfiniteRain** [comment]
Hey @nring

First of all, apologies for not answering earlier. This issue has somehow slipped through the cracks. In previous versions of the Conversations SDK, something like that was indeed possible, however, due to a multitude of internal refactors, the `args` argument can no longer be used for filtering. This looks like a bug and we're currently looking into fixing it. I will leave this issue up for now.

**Comment by berkus** [comment]
@nring hi, there was a bit of confusion about this.

First, the sorting of the conversations has been removed from the SDK because it is largely a client-side-specific action - after you fetch the subscribed conversations you are free to sort them however you want.

Second, we are working on a better interface at the moment, that would allow to query more flexibly and with a lower overhead - we will see if sorting would be a good thing to add there (it will be present in the sort of predicate filtering, e.g. return only unread channels, or only recently updated channels - then this would also include appropriate sorting).
